name: Release new action version
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'run release action reason'
        required: false
        type: string
        default: 'manually test'
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Check Go Version and Install Go Dep
        run: |
          go version
          go mod vendor

      - name: Build
        run: make all

      - name: Generate Release.txt
        run: |
          echo ${{ github.sha }} > Release.txt
          cat Release.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/main-linux-amd64
            bin/main-linux-arm64
            bin/main-linux-ppc64le
            bin/main-linux-s390x
            bin/main-darwin-amd64
            bin/main-darwin-arm64
            bin/main-windows-amd64.exe
            Release.txt
            LICENSE
